#!/bin/bash

gr="\e[1;32m"
rd="\e[1;31m"
no="\e[1;0m"
bl="\e[1;36m"
yl="\e[1;33m"

update(){
clear
echo -e "    ${bl} --------------------------------------"
echo -e "    ${rd}|               Install                |"
echo -e "    ${bl} --------------------------------------${no}\n"
	apt-get update && apt-get upgrade -y
	apt-get install screenfetch neofetch wget -y
echo
}

kali(){

echo -e "${rd}"

echo " ██ ▄█▀    ▄▄▄          ██▓        ██▓"
echo " ██▄█▒    ▒████▄       ▓██▒       ▓██▒"
echo "▓███▄░    ▒██  ▀█▄     ▒██░       ▒██▒"
echo "▓██ █▄    ░██▄▄▄▄██    ▒██░       ░██░"
echo "▒██▒ █▄    ▓█   ▓██▒   ░██████▒   ░██░"
echo "▒ ▒▒ ▓▒    ▒▒   ▓▒█░   ░ ▒░▓  ░   ░▓  "
echo "░ ░▒ ▒░     ▒   ▒▒ ░   ░ ░ ▒  ░    ▒ ░"
echo "░ ░░ ░      ░   ▒        ░ ░       ▒ ░"
echo "░  ░            ░  ░       ░  ░    ░  "
echo "                                      "
echo
}


start() {
	clear
	neofetch;
	echo -e "${bl}Make sure You have Minimum ${gr}15GB ${bl}of free storage."
	sleep 3; clear; screenfetch; sleep 2; clear; kali
	echo -e "${rd}Hit ENTER to continue...."
	read
	clear; screenfetch; sleep 3.2; clear; kali;
	echo
	wget -O install-nethunter-termux https://offs.ec/2MceZWr
	chmod +x install-nethunter-termux
	clear
	./install-nethunter-termux

}

# clear

help(){
	clear; kali
	echo
	echo -e "${bl}Made by ${gr}Adarsh Addee ${bl}with <3"
	echo -e "${no}I'm not the owner of Kali-Liunx-Nethunter-OS"
	echo
	echo -e "   ${gr}*  ${bl}This script will help you to install ${rd}Kali-Nethunter${bl} in Termux."
	echo
	echo -e "   ${gr}*  ${rd}Great Powers ${bl}comes with ${rd}Great Responsiblities."
	echo
	echo -e "${no}Here are some commands.........?"
	echo -e "${gr}-> Commands                ${bl}-> Description"
	echo -e "${gr}  -h | --help              ${bl}- Open help.\n"
	echo -e "${gr}  -u | --update            ${bl}- Install Pacakages\n"
	echo -e "${gr}  -s | --start             ${bl}- Start Installation.\n"
	echo -e "${gr}  -c | --commands          ${bl}- Show commands.\n"
	echo
	echo -e "${no}visit 'https://www.kali.org/docs/nethunter/nethunter-rootless' for more info."
	echo
	echo -e "${yl}Wants to Connect with me:"
	echo
	echo -e "${gr}Search ${bl}Adarsh Addee ${gr}on Google and YouTube and support. ${rd}<3"
	echo
}

commands(){
clear; kali; echo
echo -e "\n${rd}List of all available commands after successfull installation\n"
echo
echo -e "   ${gr}nethunter                  ${bl}- start Kali Nethunter In CLI Mode"
echo
echo -e "   ${gr}nethunter kex passwd       ${bl}- configure the KeX password (need only before 1st use)"
echo
echo -e "   ${gr}nethunter kex &            ${bl}- start Kali Nethunter in GUI Mode"
echo
echo -e "   ${gr}nethunter kex stop         ${bl}- stop Kali Nethunter GUI Mode"
echo
echo -e "   ${gr}nethunter <command>        ${bl}- run <command> in Nethunter Environment"
echo
echo -e "   ${gr}nethunter -r               ${bl}- start Kali Nethunter CLI as root"
echo
echo -e "   ${gr}nethunter -r kex passwd    ${bl}- configure KeX password for root"
echo
echo -e "   ${gr}nethunter -r kex &         ${bl}- start Kali Nethunter GUI as root"
echo
echo -e "   ${gr}nethunter -r kex stop      ${bl}- stop Kali Nethunter GUI as root"
echo
echo -e "   ${gr}nethunter -r kex kill      ${bl}- kill all KeX sessions"
echo
echo -e "   ${gr}nethunter -r <command>     ${bl}- run <command> in Nethunter Environment as root"
echo
echo
echo -e "${no}visit 'https://www.kali.org/docs/nethunter/nethunter-rootless/' for more info"
echo
}

menu(){
case $1 in
	"--help" | "-h")
		help;;

	"--commands" | "-c")
		commands;;

	"--start" | "-s")
		start;;

	"--update" | "-u")
		update;;

	*)
		help;;
		
esac
}

menu $1
if [ $? != 0 ]; then
	clear; help;
fi
